### ISSUE TITLE
Error in CARD_deconvolution

### ISSUE THREAD

**Issue by cherrie-g** [YingMa1993/CARD#11]
Hi
I met a error in CARD_deconvolution cause my data is a little big I think.
This is the error message:
```
Error in asMethod(object) : 
  Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 102
Calls: CARD_deconvolution ... rowGrpMeans -> as.matrix -> as.matrix -> as -> asMethod
Execution halted
```

And I tried to convert the format of `CARD_obj@sc_eset@assays@data$counts` and `CARD_obj@spatial_countMat` from dgCMatrix to matrix using a self-defined function. But it still called the same error. Any solution of this error? or I convert the wrong dgCMatrix?

Bests.

**Comment by YingMa0107** [comment]
Hi @cherrie-g, 

Thank you very much for your interest in our package! The error seems to come from the function that I used in the process of constructing the single-cell RNAseq reference basis matrix. So could you please tell me what is the dimension of your single-cell RNA-seq reference data?

**Comment by cherrie-g** [comment]
Sure, the dimension pf my sc data is `3000 978734`, 3000 genes and 978734 cells.

**Comment by YingMa0107** [comment]
Hi @cherrie-g, 

Sorry for the late reply. The error comes from the function when creating reference basis matrix of the single cell RNAseq because of the memory issue since your scRNAseq data is huge. One way to solve this quickly is to subset the cells per each cell type, which is also  adopted by many other deconvolution methods in their source code. Based on my previous experience on other datasets, you can subset 1000 cells for each cell type (if < 1000 cells, just take them all), it should not affect the general performance of CARD. 

Hope this is helpful!

**Comment by cherrie-g** [comment]
It works! Thank you so much!

**Comment by Li-ZhiD** [comment]
Hi, @YingMa0107 , I am using CARD for large Stereo-seq data, Is there a difference between analyzing the data in smaller chunks versus analyzing it all together (high memory requried)?
