### ISSUE TITLE
The area annotation of the PDAC-A spots

### ISSUE THREAD

**Issue by lzygenomics** [YingMa1993/CARD#20]
Hi~@YingMa0107 

Thanks for the fascinating work! I am trying to reproduce Fig4d. Could you mind sharing the annotation information of Fig 4a about the regions where different spots belong?

Best~

**Comment by YingMa0107** [comment]
Hi @lzygenomics, 

Thank you very much for your interest in our package. I have deposited the annotation information of Fig4A here [https://github.com/YingMa0107/CARD/tree/master/data](url) 

Basically, the annotation is manually annotated based on the H&E image. Note that we only annotated the spatial locations that are common in all the benchmarked Methods' results for fair comparison, so there might be 1~2 spatial locations that were not annotated due to the missingness of the spots in other methods' results. 

Hope this is helpful!

**Comment by lzygenomics** [comment]
> Hi @lzygenomics,
> 
> Thank you very much for your interest in our package. I have deposited the annotation information of Fig4A here [https://github.com/YingMa0107/CARD/tree/master/data](url)
> 
> Basically, the annotation is manually annotated based on the H&E image. Note that we only annotated the spatial locations that are common in all the benchmarked Methods' results for fair comparison, so there might be 1~2 spatial locations that were not annotated due to the missingness of the spots in other methods' results.
> 
> Hope this is helpful!

Thanks for your help !

Best~
