### ISSUE TITLE
Error in running CARD_deconvolution() function

### ISSUE THREAD

**Issue by Anthony-Ramnauth** [YingMa1993/CARD#24]
When I try to run the deconvolution I get the following error:

```
Error in CARDref(XinputIn = as.matrix(Xinput_norm), UIn = as.matrix(B),  : 
  std::bad_alloc
```
I'm assuming there is some problem with converting a sparse matrix to a matrix? Maybe too much memory demand? or allocation of storage for each iteration causing a memory leak? I will try to run this on a computing cluster to see if it works.

**Comment by YingMa0107** [comment]
Hi @Anthony-Ramnauth, 

Thank you very much for your interest in our package! 

It might be due to the large matrix issue here. Could you please tell me more about the details? i.e. What is the dimension of your spatial transcriptomics data as well as the single cell RNA-seq reference dataset? If the spatial transcriptomics dataset has more than 100k spatial locations, it might cause the error here due to the memory issue. 

Best,
Ying
