### ISSUE TITLE
Error in CARD.visualize.gene: selected genes that are not in the expression data!

### ISSUE THREAD

**Issue by JerryZhang-1222** [YingMa1993/CARD#27]
Hello, thank you so much for providing such a good tool.

I am tring to visualize a gene of interest using `CARD.visualize.gene`. However, the CARD object seems to have excluded this gene. 

Here are all the codes. I once thought that this might be caused be the `minCountGene` and `minCountSpot` so I set these two parameters as 0, but I still can't find the gene I want.
```
CARD_all <- createCARDObject(
  sc_count = sc_count,
  sc_meta = sc_meta,
  spatial_count = spatial_count,
  spatial_location = spatial_location,
  ct.varname = "names_f1",
  ct.select = unique(sc_meta$names_f1),
  sample.varname = "orig.ident",
  minCountGene = 0,
  minCountSpot = 0)

#Deconvolution using CARD
CARD_all <- CARD_deconvolution(CARD_object = CARD_all)

#Refined Grid
CARD_all <- CARD.imputation(CARD_all,NumGrids = 3000,ineibor = 10,exclude = NULL)
location_imputation <- cbind.data.frame(x=as.numeric(sapply(strsplit(rownames(CARD_all@refined_prop),split="x"),"[",1)),
                                       y=as.numeric(sapply(strsplit(rownames(CARD_all@refined_prop),split="x"),"[",2)))
rownames(location_imputation) <- rownames(CARD_all@refined_prop)
CARD.visualize.gene(
  spatial_expression = CARD_all.FC@refined_expression,
  spatial_location = location_imputation,
  gene.visualize = c("Homer1"),
  colors = NULL,
  NumCols = 1)

Error in CARD.visualize.gene(spatial_expression = CARD_all.FC@refined_expression,  : 
  There existing selected genes that are not in the expression data!
```

Is there some sort of ways to include all the genes? Thank you so much again.

**Comment by YingMa0107** [comment]
Hi @JerryZhang-1222, 

Thank you very much for your interest in our package! 

This gene was excluded is because in CARD, we only select the informative genes for constructing the reference basis matrix and then perform deconvolution based on these informative genes. Details of the selection of these informative genes are in the Methods section (See Construction of the Basis Matrix). The imputation is also based on using the constructed reference basis matrix. It might be difficult to include all the genes at this stage for the imputation step. 


Best,
Ying

**Comment by JerryZhang-1222** [comment]
> Hi @JerryZhang-1222,
> 
> Thank you very much for your interest in our package!
> 
> This gene was excluded is because in CARD, we only select the informative genes for constructing the reference basis matrix and then perform deconvolution based on these informative genes. Details of the selection of these informative genes are in the Methods section (See Construction of the Basis Matrix). The imputation is also based on using the constructed reference basis matrix. It might be difficult to include all the genes at this stage for the imputation step.
> 
> Best, Ying

Dear Ma,

Thank you for your reply. You have provided an excellent tool. 

I understand your words, but may I ask again that if there are any chance I can inclue more genes of interset into the basis matrix? Thank you again for your reply.

Yours,
Feiyang

**Comment by NicolaasVanRenne** [comment]
same problem here

**Comment by YingMa0107** [comment]
Hi @NicolaasVanRenne, 

Thank you for your interest!

Currently, the package contains the refined gene expression only for the informative genes. We may consider modifying the code by adding more genes back in the refined gene expression data in the future!

Best,
Ying

**Comment by NicolaasVanRenne** [comment]
Hello @YingMa0107 

I tried adding a few genes of interests, and it works perfectly fine (and lowered fc from 1.25 to 0.5). 

Adding all genes destroys the CARD performance, so I understand why you deleted them.

I highy recommend an option to add a selection of genes of interest. Especially since you remove all marker genes which is probably what we are most interested in :)

Have a nice day and the enhanced resolution is amazing I absolutely LOVE it!

**Comment by YingMa0107** [comment]
Hi @NicolaasVanRenne, 

Thank you for your feedback, and I'm glad to hear that you found the enhanced resolution function helpful!

I appreciate your suggestion regarding the inclusion of more genes or selected genes for the high-resolution gene expression prediction. I will try to look into updating the code to accommodate this option. I'll keep you informed about any progress I make in that regard.

Have a great day!

Best,
Ying

**Comment by NicolaasVanRenne** [comment]
For those of you that want to expore what I did, I created a forked version called CARD+

# CARD+: CARD with your genes of interest
Often when using CARD, interesting genes are filtered away to make the algorithm reliable. This CARD version bypasses the gene selection in two ways that are different from the original version:

1) For the basis matrix, I selected the genes with a mean expression level in a given cell type of at least 0.5 (instead of 1.25) log-fold higher than its mean expression level across all remaining cell. This increases the number of genes without affecting algorithm quality (at least, in my data sets).
2) You can add your genes of interest by creating a vector 'my.genes' containing your genes of interest. e.g.
``` r
 my.genes = c("GENE1","GENE2")
``` 
Then just run the whole thing like you would run CARD.

To install this version, just run 
``` r
library(devtools)
install_github("NicolaasVanRenne/CARD")
library(CARD)"
``` 
Kind regards and good luck, 
Nicolaas Van Renne
