### ISSUE TITLE
Error in CARD visualization of proportions

### ISSUE THREAD

**Issue by ShraddhaRaghuram** [YingMa1993/CARD#41]
Hi!
I am trying to use the visualization function of CARD to visualize the cell type proportions. However, I am getting the same error repeatedly. I tried changing the argument variables to data frames but it doesn't work. Could you help me with a solution to this? This is the error that I get.
![image](https://user-images.githubusercontent.com/63044070/235664329-acb78a0b-6d28-4b9e-8ce4-aca927112a8d.png)
Thanks, and kind regards,
Shraddha

**Comment by YingMa0107** [comment]
Hi @ShraddhaRaghuram, 

Thank you for your interest in our package!

The error occurred because the apply function works only with data frames or matrices. In your case, since you are visualizing only one cell type, the res_CARD is a vector, which is a subset of CARD_A1@Proportion_CARD. This is why the error appeared. To address this issue, I have made changes to the CARD.visualize.prop function. It is now capable of handling one cell type visualization. You can find the updated code on my GitHub page, or you can simply reinstall the CARD package and try calling CARD.visualize.prop again. It should now work well in your case. Please let me know if you continue to experience any issues. Thank you!

Best,
Ying
