### ISSUE TITLE
CARD Object does not look like the original tissue

### ISSUE THREAD

**Issue by chrkuo** [YingMa1993/CARD#51]
Hi, I deconvoluted my CARD object but it does not look like the original tissue at all. what could be causing this? 

this is deconvoluted from CARD
<img width="872" alt="image" src="https://github.com/YingMa0107/CARD/assets/119452428/e1fb23e5-8b46-4f46-a989-511fd8ac3cf8">

but my original image looks like this: 

<img width="221" alt="image" src="https://github.com/YingMa0107/CARD/assets/119452428/62d38692-f2b4-457a-a930-90b75e4c4439">

this is such a drastic change. wondering what mightve caused it?

**Comment by YingMa0107** [comment]
Hi @chrkuo, 

Thank you for your interest in CARD. I saw that you closed this issue, did you solve this somehow? It should be the same shape with the original input of your tissue. Thanks.

Best,
Ying

**Comment by chrkuo** [comment]
> Hi @chrkuo, 
> 
> 
> 
> Thank you for your interest in CARD. I saw that you closed this issue, did you solve this somehow? It should be the same shape with the original input of your tissue. Thanks.
> 
> 
> 
> Best,
> 
> Ying

Hi @YingMa0107 thank you! I did. It was because i was inputting a unfiltered metadata. 

Quick question - I have used the same scRNA seq input for deconvolution using DWLS and CARDS but getting quite different output proportions. Is it because for CARDs im not using normalized data. 

Which brings me to my next question if i should be using normalized data. 

Thank you

**Comment by chrkuo** [comment]
@YingMa0107 wanted to follow up regarding normalization or not or should i just use raw?

**Comment by YingMa0107** [comment]
Hi @chrkuo, 

Sorry for the late reply.

To clarify, when you mention "normalized data", are you referring to normalized scRNA-seq count data or normalized spatial transcriptomics data or both normalized?

For our methodology, it's optimal if both the single cell data and the spatial data are in count form. This is because we derive the reference basis matrix by examining the relationship between mean gene expression (from the reference basis matrix) and mixed gene expression (from spatial data). I've experimented with normalized scRNA-seq data and found satisfactory performance. For the spatial transcriptomics (ST) data, I recommend using the raw counts. Regarding the scRNA-seq reference data, the choice depends on what's available: if raw count data is accessible, it's preferable. However, if only normalized scRNA-seq data is available, it should still work effectively. Do keep in mind, though, that both the scRNA-seq and spatial data must always be non-negative, given that CARD is built on a Non-negative Matrix Factorization (NMF) framework.

Best,
Ying
